AWSTemplateFormatVersion: 2010-09-09
Description: TheBetterStore VPC definition

Parameters:
  Environment:
    Type: String

  VPCCidr:
    Type: String
    Default: 10.1.0.0/16

  PublicSubnetACidr:
    Type: String
    Default: 10.1.0.0/24

  PublicSubnetBCidr:
    Type: String
    Default: 10.1.1.0/24

  PublicSubnetCCidr:
    Type: String
    Default: 10.1.2.0/24

  DbPrivateSubnetACidr:
    Type: String
    Default: 10.1.3.0/24

  DbPrivateSubnetBCidr:
    Type: String
    Default: 10.1.4.0/24

  DbPrivateSubnetCCidr:
    Type: String
    Default: 10.1.5.0/24

  AppPrivateSubnetACidr:
    Type: String
    Default: 10.1.6.0/24

  AppPrivateSubnetBCidr:
    Type: String
    Default: 10.1.7.0/24

  AppPrivateSubnetCCidr:
    Type: String
    Default: 10.1.8.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC

  FlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "vpc-flow-logs.amazonaws.com"

  PublishCloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-PublishCloudWatchLogsPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
            Resource: "*"
      Roles:
        - !Ref FlowLogsRole

  DHCPOptions:
    Type: "AWS::EC2::DHCPOptions"
    Properties:
      DomainName: !Sub '${AWS::Region}.compute.internal'
      DomainNameServers:
        - AmazonProvidedDNS
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-DHCPOptions

  VPCDHCPOptionsAssociation:
    Type: "AWS::EC2::VPCDHCPOptionsAssociation"
    Properties:
      DhcpOptionsId: !Ref DHCPOptions
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-InternetGateway

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicRT"
      VpcId: !Ref VPC

  DbPrivateART:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateART"
      VpcId: !Ref VPC

  DbPrivateBRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateBRT"
      VpcId: !Ref VPC

  DbPrivateCRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateCRT"
      VpcId: !Ref VPC

  AppPrivateART:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateART"
      VpcId: !Ref VPC

  AppPrivateBRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateBRT"
      VpcId: !Ref VPC

  AppPrivateCRT:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateCRT"
      VpcId: !Ref VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref PublicSubnetACidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnetA"
      VpcId: !Ref VPC

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref PublicSubnetBCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnetB"
      VpcId: !Ref VPC

  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}c"
      CidrBlock: !Ref PublicSubnetCCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnetC"
      VpcId: !Ref VPC

  DbPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref DbPrivateSubnetACidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateSubnetA"
      VpcId: !Ref VPC

  DbPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref DbPrivateSubnetBCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateSubnetB"
      VpcId: !Ref VPC

  DbPrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}c"
      CidrBlock: !Ref DbPrivateSubnetCCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-DbPrivateSubnetC"
      VpcId: !Ref VPC

  AppPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Ref AppPrivateSubnetACidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateSubnetA"
      VpcId: !Ref VPC

  AppPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: !Ref AppPrivateSubnetBCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateSubnetB"
      VpcId: !Ref VPC

  AppPrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}c"
      CidrBlock: !Ref AppPrivateSubnetCCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppPrivateSubnetC"
      VpcId: !Ref VPC

  PublicSubnetARTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnetA

  PublicSubnetBRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnetB

  PublicSubnetCRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnetC

  DbPrivateSubnetARTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DbPrivateART
      SubnetId: !Ref DbPrivateSubnetA

  DbPrivateSubnetBRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DbPrivateBRT
      SubnetId: !Ref DbPrivateSubnetB

  DbPrivateSubnetCRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DbPrivateCRT
      SubnetId: !Ref DbPrivateSubnetC

  AppPrivateSubnetARTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AppPrivateART
      SubnetId: !Ref AppPrivateSubnetA

  AppPrivateSubnetBRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AppPrivateBRT
      SubnetId: !Ref AppPrivateSubnetB

  AppPrivateSubnetCRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref AppPrivateCRT
      SubnetId: !Ref AppPrivateSubnetC

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicInternetRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # No NatGw's here yet, test envt only avoiding costs
Outputs:
  VPCId:
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}:VPC:Id'

  VPCCidr:
    Value: !Ref VPCCidr
    Export:
      Name: !Sub '${AWS::StackName}:VPC:Cidr'

  PublicSubnetAId:
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub '${AWS::StackName}:PublicSubnetA:Id'

  PublicSubnetBId:
    Value: !Ref PublicSubnetB
    Export:
      Name: !Sub '${AWS::StackName}:PublicSubnetB:Id'

  PublicSubnetCId:
    Value: !Ref PublicSubnetC
    Export:
      Name: !Sub '${AWS::StackName}:PublicSubnetC:Id'

  DbPrivateARTId:
    Value: !Ref DbPrivateART
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateART:Id'

  DbPrivateBRTId:
    Value: !Ref DbPrivateBRT
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateBRT:Id'

  DbPrivateCRTId:
    Value: !Ref DbPrivateCRT
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateCRT:Id'

  AppPrivateRTAId:
    Value: !Ref AppPrivateART
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateRTA:Id'

  AppPrivateRTBId:
    Value: !Ref AppPrivateBRT
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateRTB:Id'

  AppPrivateRTCId:
    Value: !Ref AppPrivateCRT
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateRTC:Id'

  AppPrivateSubnetAId:
    Value: !Ref AppPrivateSubnetA
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateSubnetA:Id'

  AppPrivateSubnetBId:
    Value: !Ref AppPrivateSubnetB
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateSubnetB:Id'

  AppPrivateSubnetCId:
    Value: !Ref AppPrivateSubnetC
    Export:
      Name: !Sub '${AWS::StackName}:AppPrivateSubnetC:Id'

  DbPrivateSubnetAId:
    Value: !Ref DbPrivateSubnetA
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateSubnetA:Id'

  DbPrivateSubnetBId:
    Value: !Ref DbPrivateSubnetB
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateSubnetB:Id'

  DbPrivateSubnetCId:
    Value: !Ref DbPrivateSubnetC
    Export:
      Name: !Sub '${AWS::StackName}:DbPrivateSubnetC:Id'